name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04-xl
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 91860b34f52e498913e69bef3fc734fdf1ff817c
          deno-binary-name: "deno_doc"

      - name: "Reference: install"
        working-directory: "reference_gen"
        run: DENO_FUTURE=1 deno install

      - name: "Reference: generate types"
        working-directory: "reference_gen"
        run: DENO_FUTURE=1 deno task types

      - name: "Reference: generate docs"
        working-directory: "reference_gen"
        run: deno_doc task doc

      - name: Build
        env:
          ORAMA_CLOUD_INDEX_ID: ${{ vars.ORAMA_CLOUD_INDEX_ID }}
          ORAMA_CLOUD_API_KEY: ${{ secrets.ORAMA_CLOUD_API_KEY }}
        run: DENO_FUTURE=1 deno task build

      - name: Run server
        working-directory: _site
        run: deno run --allow-read=. --allow-net --allow-env --allow-import=cdn.jsdelivr.net,raw.githubusercontent.com,deno.land,jsr.io server.ts

      - name: Link checker
        env:
          DOCS_ROOT: "http://localhost:8000"
        run: deno run --allow-net .github/workflows/link_checker.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deno-docs"
          entrypoint: "server.ts"
          root: "_site"
