name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04-xl
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ea8bf0945ac93a16a3d8df2470c70d9cf1c36172
          deno-binary-name: "deno_doc"

      - name: "Reference: install"
        working-directory: "reference_gen"
        run: DENO_FUTURE=1 deno install

      - name: "Reference: generate types"
        working-directory: "reference_gen"
        run: deno task types

      - name: "Reference: generate docs"
        working-directory: "reference_gen"
        run: deno_doc task doc

      - name: Build
        env:
          ORAMA_CLOUD_INDEX_ID: ${{ vars.ORAMA_CLOUD_INDEX_ID }}
          ORAMA_CLOUD_API_KEY: ${{ secrets.ORAMA_CLOUD_API_KEY }}
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deno-docs"
          entrypoint: "server.ts"
          root: "_site"
